apiVersion: apps/v1
kind: Deployment
metadata:
  name: %APP_NAME%
spec:
  replicas: %APP_COUNT%
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: %APP_NAME%
  template:
    metadata:
      labels:
        app: %APP_NAME%
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - %SERVER_TYPE%
      containers:
      - image: %DOCKER_IMAGE%
        imagePullPolicy: Always
        name: %APP_NAME%
        env:
        - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
          value: '%BUILD_NUMBER%'
        - name: VAULT_TOKEN
          value: '%VAULT_TOKEN%'
        - name: VAULT_SECRET
          value: '%VAULT_SECRET%'
      imagePullSecrets:
        - name: %K8S_REGISTRY%
---
apiVersion: v1
kind: Service
metadata:
  name: %APP_NAME%
spec:
  ports:
  - name: http
    targetPort: %APP_PORT%
    port: 80
  selector:
    app: %APP_NAME%
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: %APP_NAME%
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rewrite-target: %APP_REWRITE_PATH%
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: %DOMAIN_NAME%
    http:
      paths:
      - path: %APP_PATH%
        backend:
          serviceName: %APP_NAME%
          servicePort: http
